
server:
  port: 8025

spring:
  application:
    name: seata-order-test
  datasource:
    username: root
    password: 12345dfg
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order_test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public
        group: DEFAULT_GROUP
    alibaba:
      seata:
        tx-service-group: beijing #配置事务分组


seata:
  registry:
#    配置seata注册中心
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848  # seata server 所在的nacos服务地址
      application: seata-server # seata的服务名
      username: nacos
      password: nacos
      group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848  # seata server 所在的nacos服务地址
      username: nacos
      password: nacos
      group: SEATA_GROUP




